# Generated by Django 5.0.3 on 2024-10-23 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilityhub', '0006_alter_person_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interaction_id', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
                ('code_location', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('levelname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('json_log', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
