# Generated by Django 5.0.3 on 2024-10-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilityhub', '0007_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.CharField(max_length=50),
        ),
    ]
